version: '3'

services:
  
  backend:
    build: .
    container_name: api-ocr
    volumes:
      - ./log:/log
      - ./input:/input
      - ./output:/output
      - ./weights:/weights
    entrypoint: ["sh", "./docker-entrypoint.sh"]
    ports:
      - "5000:5000"

  frontend:
    build: /Frontend/.
    container_name: FE-ocr
    ports:
      - "3000:3000"
    depends_on:
      - backend

